#!/bin/bash
# Setup script for the cron job

# Ensure we are in the project root directory
cd "$(dirname "$0")"
PROJECT_DIR="$(pwd)"

# Check if GEMINI_API_KEY is set or passed as argument
API_KEY="${GEMINI_API_KEY:-$1}"

if [ -z "$API_KEY" ]; then
    echo "Error: GEMINI_API_KEY is not set in the environment or passed as an argument."
    echo "Usage: ./setup_cron.sh <YOUR_GEMINI_API_KEY>"
    exit 1
fi

# Create the wrapper script that cron will execute
CRON_WRAPPER="$PROJECT_DIR/cron_wrapper.sh"

cat << EOF > "$CRON_WRAPPER"
#!/bin/bash
# Autogenerated script for crontab execution

# Navigate to project directory
cd "$PROJECT_DIR"

# Set API Key
export GEMINI_API_KEY="$API_KEY"

# Create outputs dir if it doesn't exist
mkdir -p outputs

# Activate virtual environment and run the batch job, logging output
source .venv/bin/activate
echo "=== Cron Job Run: \$(date) ===" >> outputs/cron_run.log
python3 run_all.py >> outputs/cron_run.log 2>&1
echo "=== Finished: \$(date) ===" >> outputs/cron_run.log
EOF

chmod +x "$CRON_WRAPPER"
echo "Generated cron wrapper script: $CRON_WRAPPER"

# Check if the cron job is already registered to avoid duplicates
CRON_JOB="0 9 * * 1 \"$CRON_WRAPPER\"" # Every Monday at 9:00 AM

# Read existing crontab, excluding any previous reference to this project's cron wrapper
EXISTING_CRON=$(crontab -l 2>/dev/null | grep -v "$CRON_WRAPPER")

# Write new crontab
(
echo "$EXISTING_CRON"
echo "$CRON_JOB"
) | crontab -

echo "--------------------------------------------------------"
echo "✅ Cron job successfully scheduled!"
echo "Schedule: Every Monday at 9:00 AM"
echo "Log file: $PROJECT_DIR/outputs/cron_run.log"
echo "To view current crontab: crontab -l"
echo "--------------------------------------------------------"
